### ISSUE TITLE
I knew there was something

### ISSUE THREAD

**Issue by skoppe** [ValhallaLib/valhalla_ecs#17]
So it turns out that `shared static size_t id` *does* create a global shared, just like __gshared does. The difference is that with shared the type is also shared, whereas with __gshared it isn't.

I also misunderstood the point of the function: it is to create one unique id per type. Not, like I thought, a sequence of unique ids per type.

Closing it.

**Comment by iK4tsu** [comment]
Yes, it is to create a unique id per type. The variable continues to be thread-local storage, but because it is `static` and `shared` it simulates a `global shared` variable. This ensures all threads produce the same id for the same type, this was why I also assumed the function as `pure`. Now, this does not have an advantage over creating the ids in the main thread, it's kind of useless to it in multiple threads as the `id` variable will keep getting locked by each thread to have them all synced to the same value, which is just the same as to do it sequentially in the main thread, if not more costly.

**Comment by iK4tsu** [comment]
However, if someone were to do it, it is guaranteed to work.
