### ISSUE TITLE
A library should not contain `dub.selections.json` 

### ISSUE THREAD

**Issue by drug007** [ValhallaLib/valhalla_ecs#9]
This file should be generated by the library user application not by the library itself.

**Comment by ljmf00** [comment]
Dependency lock files should be present on its project dependencies, whether it's a library or an executable, for a variety of reasons ranging from dependency caching to reproducibility. Lock files are essential for every project if you want the user to build the library correctly and make it reproducible, in a dependency context, otherwise, it will lead to non-pinning dependencies.

In this case, valhalla_ecs is pinning every dependency it uses, so there's no need. But in general, every distributed project should have `dub.selections.json` tracked.

**Comment by iK4tsu** [comment]
I was under the impression that lock files should be committed as they contain hold the versions of the dependencies used to build it. However upon some investigation into `dub.selections.json` it's bit of a miss match between must and mustn't with the majority inclining to mustn't if the project is a library and must if the project is an application. From my understanding `dub.json` specifies the optional dependencies and `dub.selections.json` then chooses which ones are selected. In this lib having `dub.selections.json` ins't really an issue, and neither is removing it. That said, I read that `dub` might be a little "broken" about such things. So I can remove it if it's preferred by you. But before that I would like an explanation of why I should because I'm not really sold.

**Comment by drug007** [comment]
Only executable project should track dub.selection.json. Libraries should depends on versions from the projects (executable) that use them. In other case you easily can fail to build the executable project because versions from the executable project conflicts to versions from its libraries or libraries version conflicts each other. The only versions holder is the executable project. It defines what version should be used and so no version conflict could happen.
But of course it's your choice first of all.

**Comment by iK4tsu** [comment]
I see, makes sense. I might've had the wrong idea about `dub.selections.json`.

**Comment by FFY00** [comment]
I think the problem here is dub being dumb and looking at the lock file of libraries. Having a lock file in a library should not impact its use as a dependency. Lock files do not represent dependency requirements, they represent environments. They are useful for testing and managing the dependency directly, but should have no impact whatsoever outside of that. Sorry for this description, as I have been very frustrated with dub and its decisions for a few years now, but dub is just being stupid.

**Comment by ljmf00** [comment]
> Only executable project should track dub.selection.json. Libraries should depends on versions from the projects (executable) that use them. In other case you easily can fail to build the executable project because versions from the executable project conflicts to versions from its libraries or libraries version conflicts each other. The only versions holder is the executable project. It defines what version should be used and so no version conflict could happen.
But of course it's your choice first of all.

I tested it by myself. Dub just ignores `dub.selections.json` for its dependencies. Let's say that we have `pkg1` with `0.9.1` versions locked on `dub.selections.json`.

```json
{
	"name": "pkg1",
	"targetType": "library",
	"dependencies": {
		"vibe-d": "~>0.9.1"
	}
}
```

And a `pkg2` without a lock file.
```json
{
	"name": "pkg2",
	"dependencies": {
		"pkg1": "*"
	}
}
```

If we run `dub` on `pkg2`, `dub.selections.json` will have `0.9.3`, which is the latest version that satisfies the version dependency.

> I think the problem here is dub being dumb and looking at the lock file of libraries. Having a lock file in a library should not impact its use as a dependency. Lock files do not represent dependency requirements, they represent environments. Building an app that depends on this project is clearly a different environment. They are useful for testing and managing the dependency directly, but should have no impact whatsoever outside of that. Sorry for this description, as I have been very frustrated with dub and its decisions for a few years now, but dub is just being stupid.

So it seems that `dub` works as intended and makes the usage of lock files correctly. As @FFY00 said, lock files are intended to describe an environment. This will be able to reproduce the library build.
Although I totally agree that some dub philosophy is not well discussed and could lead to bad decisions, such as https://github.com/dlang/dub/issues/1245, https://github.com/dlang/dub/issues/2076 and other things like static linking everything by default, no pkg-config support, and many many other things.

**Comment by drug007** [comment]
Ok. I can be wrong about the reasons of the recommendation to commit dub.selection.json for applications only and do not commit it for libraries. It is really old recommendation. I have  no time to investigate it, it is a big area.
